pdflatex functionalSpecificationPS.tex
makeindex -s functionalSpecificationPS.ist -o functionalSpecificationPS.gls functionalSpecificationPS.glo
pdflatex functionalSpecificationPS.tex
evince functionalSpecificationPS.pdf
